server:
  port: 3000
spring:
  application:
    name: Bank-Application
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/